### ISSUE TITLE
Can't Install on Latest Lucee

### ISSUE THREAD

**Issue by jamiejackson** [markussackmann/extension-redis-single#5]
I had been using this extension for years (thanks @markussackmann ) but in the latest version of Lucee (5.3.10.97 ) , I get an exception when installing.

```
lucee.runtime.exp.NativeException: Uses constraint violation. Unable to resolve resource ${bundlename} [${bundlename} [73](R 73.0)] because it is exposed to package 'org.apache.commons.pool2' from resources org.apache.commons.pool2 [org.apache.commons.pool2 [77](R 77.0)] and org.apache.commons.commons-pool2 [org.apache.commons.commons-pool2 [65](R 65.0)] via two dependency chains.
Chain 1:
${bundlename} [${bundlename} [73](R 73.0)]
require: (&(osgi.wiring.bundle=org.apache.commons.pool2)(bundle-version>=2.4.1))
|
provide: osgi.wiring.bundle: org.apache.commons.pool2
org.apache.commons.pool2 [org.apache.commons.pool2 [77](R 77.0)]
Chain 2:
${bundlename} [${bundlename} [73](R 73.0)]
require: (&(osgi.wiring.bundle=redis.clients.jedis)(bundle-version>=2.7.2))
|
provide: [redis.clients.jedis [74](R 74.0)] osgi.wiring.bundle; {bundle-version=2.7.2, osgi.wiring.bundle=redis.clients.jedis}
redis.clients.jedis [redis.clients.jedis [74](R 74.0)]
import: (&(osgi.wiring.package=org.apache.commons.pool2)(version>=2.3.0)(!(version>=3.0.0)))
|
export: osgi.wiring.package: org.apache.commons.pool2
org.apache.commons.commons-pool2 [org.apache.commons.commons-pool2 [65](R 65.0)] Unresolved requirements: [[${bundlename} [73](R 73.0)] osgi.wiring.bundle; (&(osgi.wiring.bundle=redis.clients.jedis)(bundle-version>=2.7.2))]
at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
at lucee.loader.osgi.BundleUtil.start(BundleUtil.java:112)
at lucee.loader.osgi.BundleUtil.start(BundleUtil.java:108)
at lucee.runtime.osgi.OSGiUtil._start(OSGiUtil.java:1277)
at lucee.runtime.osgi.OSGiUtil._startIfNecessary(OSGiUtil.java:1230)
at lucee.runtime.osgi.OSGiUtil._loadBundle(OSGiUtil.java:534)
at lucee.runtime.osgi.OSGiUtil.loadBundle(OSGiUtil.java:509)
at lucee.commons.lang.ClassUtil.loadClassByBundle(ClassUtil.java:163)
at lucee.transformer.library.ClassDefinitionImpl.getClazz(ClassDefinitionImpl.java:117)
at lucee.runtime.config.XMLConfigAdmin.setClass(XMLConfigAdmin.java:6713)
at lucee.runtime.config.XMLConfigAdmin._updateCache(XMLConfigAdmin.java:4271)
at lucee.runtime.config.XMLConfigAdmin.updateRHExtension(XMLConfigAdmin.java:4904)
at lucee.runtime.config.XMLConfigAdmin.updateRHExtension(XMLConfigAdmin.java:4719)
at lucee.runtime.config.XMLConfigAdmin._updateRHExtension(XMLConfigAdmin.java:4701)
at lucee.runtime.tag.Admin.doUpdateRHExtension(Admin.java:4343)
at lucee.runtime.tag.Admin._doStartTag(Admin.java:781)
at lucee.runtime.tag.Admin.doStartTag(Admin.java:364)
at ext_applications_upload_cfm966$cf.__luceedebug__call(/admin/ext.applications.upload.cfm:53)
at ext_applications_upload_cfm966$cf.call(/admin/ext.applications.upload.cfm)
at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1056)
at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:948)
at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:929)
at ext_applications_cfm184$cf.__luceedebug__call(/admin/ext.applications.cfm:113)
at ext_applications_cfm184$cf.call(/admin/ext.applications.cfm)
at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1056)
at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:948)
at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:929)
at web_cfm$cf.__luceedebug__call(/admin/web.cfm:492)
at web_cfm$cf.call(/admin/web.cfm)
at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1056)
at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:948)
at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:929)
at server_cfm$cf.__luceedebug__call(/admin/server.cfm:2)
at server_cfm$cf.call(/admin/server.cfm)
at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1056)
at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:948)
at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:219)
at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44)
at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2493)
at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2478)
at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2449)
at lucee.runtime.engine.Request.exe(Request.java:45)
at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1216)
at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1162)
at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)
at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at pl.hordyjewiczmichal.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:61)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at org.apache.catalina.filters.RemoteIpFilter.doFilter(RemoteIpFilter.java:937)
at org.apache.catalina.filters.RemoteIpFilter.doFilter(RemoteIpFilter.java:988)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.osgi.framework.BundleException: Uses constraint violation. Unable to resolve resource ${bundlename} [${bundlename} [73](R 73.0)] because it is exposed to package 'org.apache.commons.pool2' from resources org.apache.commons.pool2 [org.apache.commons.pool2 [77](R 77.0)] and org.apache.commons.commons-pool2 [org.apache.commons.commons-pool2 [65](R 65.0)] via two dependency chains.
Chain 1:
${bundlename} [${bundlename} [73](R 73.0)]
require: (&(osgi.wiring.bundle=org.apache.commons.pool2)(bundle-version>=2.4.1))
|
provide: osgi.wiring.bundle: org.apache.commons.pool2
org.apache.commons.pool2 [org.apache.commons.pool2 [77](R 77.0)]
Chain 2:
${bundlename} [${bundlename} [73](R 73.0)]
require: (&(osgi.wiring.bundle=redis.clients.jedis)(bundle-version>=2.7.2))
|
provide: [redis.clients.jedis [74](R 74.0)] osgi.wiring.bundle; {bundle-version=2.7.2, osgi.wiring.bundle=redis.clients.jedis}
redis.clients.jedis [redis.clients.jedis [74](R 74.0)]
import: (&(osgi.wiring.package=org.apache.commons.pool2)(version>=2.3.0)(!(version>=3.0.0)))
|
export: osgi.wiring.package: org.apache.commons.pool2
org.apache.commons.commons-pool2 [org.apache.commons.commons-pool2 [65](R 65.0)] Unresolved requirements: [[${bundlename} [73](R 73.0)] osgi.wiring.bundle; (&(osgi.wiring.bundle=redis.clients.jedis)(bundle-version>=2.7.2))]
... 80 more
```

Unfortunately, my only other options are the [broken Lucee version](https://luceeserver.atlassian.net/browse/LDEV-4389) and the paid Ortus version.

**Comment by markussackmann** [comment]
This extension is obsolete since the official lucee extension https://github.com/lucee/extension-redis also supports redis single.

**Comment by jamiejackson** [comment]
Got it, thanks @markussackmann . Would you mind adding a note to the README? That will prevent confusion.

**Comment by jamiejackson** [comment]
I see the update, thanks. :-)
